fix: implement click `count`
puppeteer/puppeteer pull request #10069
Opened 2023-04-24 16:21 UTC by jrandolf

The `count` parameter is a new parameter that accounts for the extra number of clicks required to perform a multi-click sequence.

To ensure non-breaking behavior, the `clickCount` parameter retains the same behavior. Eventually `clickCount` will be removed in favor of count.

2023-04-24 16:28 UTC, OrKoN commented on packages/puppeteer-core/src/common/Input.ts
> +      this.#transactions = [];
what if there are scheduled transactions in there? is there any other situation when the positions have to be reset.

2023-04-24 16:46 UTC, jrandolf commented on packages/puppeteer-core/src/common/Input.ts
> +      this.#transactions = [];
`transactions` hold current ongoing transactions. It's not really a scheduler, more so a parallel state manager.

It's necessary to clear the transactions here. A navigation forces an empty state, so if there are any ongoing transactions, they will override the empty state if any of them become successful. This can happen if someone queues mouse events in parallel.

2023-04-24 17:25 UTC, OrKoN approved these changes

2023-04-25 09:48 UTC, OrKoN approved these changes

2023-04-25 10:40 UTC, OrKoN requested changes
tests are failing, PTAL

2023-04-25 11:28 UTC, OrKoN approved these changes

2023-04-25 11:28 UTC, merged