docs: added comments to the readme
puppeteer/puppeteer pull request #10552
Opened 2023-07-13 16:50 UTC by kushagraag

Added a few comments in Readme file for this project.

2023-07-13 18:03 UTC, OrKoN requested changes

2023-07-13 18:03 UTC, OrKoN commented on README.md
> +/*
I think this should not be changed

2023-07-13 18:03 UTC, OrKoN commented on README.md
> +  // Setup browser
```suggestion
  // Launch the browser and open a new blank page
```

2023-07-13 18:03 UTC, OrKoN commented on README.md
> +  // Put webpage address
```suggestion
  // Navigate the page to a URL
```

2023-07-14 05:24 UTC, kushagraag commented on README.md
> +  // Setup browser
yes, i guess your comment looks better

2023-07-14 05:28 UTC, kushagraag commented
Your comments are better, i have changed comments as per your suggestions. 
Thanks.

2023-07-14 05:52 UTC, OrKoN commented on README.md
> +/*
```suggestion
/**
```

2023-07-14 09:37 UTC, OrKoN approved these changes

2023-07-14 09:37 UTC, merged