fix: restore proxy-agent
puppeteer/puppeteer pull request #10569
Opened 2023-07-18 09:24 UTC by OrKoN

`proxy-agent` replaced the vm2 dependency with an alternative.

2023-07-18 16:53 UTC, Lightning00Blade approved these changes

2023-07-18 17:05 UTC, jrandolf requested changes
I'm not sure if we can add quick-js without making sure the implementation does not bulk up DevTools. It's also a potential security risk which needs to be vetted thoroughly by security.

2023-07-18 17:06 UTC, OrKoN commented
@jrandolf it is not shipped as part of devtools.

2023-07-19 08:48 UTC, jrandolf approved these changes

2023-07-19 08:49 UTC, jrandolf commented
I guess it's okay to have this as their implementation can always change.

2023-07-19 11:38 UTC, merged