feat!: drop support for node16
puppeteer/puppeteer pull request #10912
Opened 2023-09-14 13:44 UTC by Lightning00Blade

A good opportunity to remove some deprecation if possible/old enough.

2023-09-14 13:53 UTC, jrandolf-google requested changes

2023-09-14 13:53 UTC, jrandolf commented on packages/browsers/package.json
> +    "node": ">=18.17.1"
`>=18` everywhere.

2023-09-14 13:54 UTC, jrandolf commented
If you could, could you look back at v18 and remove anything that was deprecated?

2023-09-14 17:24 UTC, jrandolf commented
Let's create an issue that outlines what we will be deprecating from Puppeteer. For breaking releases, we should document everything so people can also chime in.

2023-09-22 18:50 UTC, OrKoN commented
I actually just remembered, we should double check the version of Node Chromium is on.

2023-09-22 18:53 UTC, OrKoN commented
yeah https://source.chromium.org/chromium/chromium/src/+/main:third_party/node/update_node_binaries;l=18;drc=5964ce8eb626cc3c18f437f194a1e9234aebe8aa

2023-10-10 16:48 UTC, Lightning00Blade commented
Note: This is required to update Rollup to v4

2024-01-24 17:12 UTC, OrKoN approved these changes

2024-01-24 18:03 UTC, jrandolf approved these changes

2024-02-02 12:12 UTC, merged

2024-02-14 05:40 UTC, dandan3100 approved these changes
GitBush/NObOdy.eth