feat: add outline (document outline) PDFs option
puppeteer/puppeteer pull request #11510
Opened 2023-12-06 19:22 UTC by bungeman

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

Yes

**Summary**

Chromium [introduced generateDocumentOutline](https://chromium.googlesource.com/chromium/src.git/+/9c2c6e785b9c644887c466ae49d7947e6c690171) in 121. This allows for a PDF document outline (sometimes known as bookmarks) to be generated from the html document outline. This CL adds a `outline` property to request this extra PDF output.

**Does this PR introduce a breaking change?**

No

**Other information**

This change is heavily based on https://github.com/puppeteer/puppeteer/pull/11182 .

2023-12-07 08:24 UTC, OrKoN requested changes
Thanks for the PR! it looks like there are some build issues. Make sure `npm run build`, `npm run format` and `npm run docs` all pass and submit any changes produced by the formatter or the doc generator.

2023-12-07 15:18 UTC, bungeman commented
Hmmm... it looks like `generateDocumentOutline` ended up in devtools-protocol [r1226504](https://github.com/ChromeDevTools/devtools-protocol/commit/9a978928587a2ba68d479fbfc0be735802a5450d) but it looks like devtools-protocol is still pinned to `r1213968`. So this will need to wait for a devtools-protocol roll. Guessing based on timing it looks like that may happen soon?

2023-12-07 15:22 UTC, OrKoN commented on test/src/page.spec.ts
> +    it('can print to PDF with outline', async () => {
btw, let's move this test to the cdp subfolder

2024-01-24 15:33 UTC, Lightning00Blade commented
@bungeman the change for Chrome 121 (https://github.com/puppeteer/puppeteer/pull/11743) landed would you please rebase and address the comments.

2024-01-30 11:34 UTC, closed without merging