refactor: fixes flakiness
puppeteer/puppeteer pull request #11807
Opened 2024-02-01 13:44 UTC by Lightning00Blade

EMPTY never emits

2024-02-01 13:46 UTC, OrKoN commented on packages/puppeteer-core/src/api/Page.ts
> -          return EMPTY;
LGTM but I wonder why was it flaky instead of failing every time?

2024-02-01 13:46 UTC, OrKoN approved these changes

2024-02-01 15:17 UTC, OrKoN commented on packages/puppeteer-core/src/api/Page.ts
> -          return EMPTY;
The EMPTY appears to be correct here and I am not sure why it's not working. The error seems to happen if we start piping why the requestsInFlight=1

2024-02-02 04:55 UTC, jrandolf requested changes
EMPTY is correct. When the number of requests in flight are greater than concurrency, we don't want to emit anything.

2024-02-02 08:04 UTC, closed without merging