chore: implement `removeExposedFunction`
puppeteer/puppeteer pull request #11984
Opened 2024-02-22 19:09 UTC by jrandolf

2024-02-23 12:20 UTC, OrKoN requested changes
it looks like some bundler tests are failing and linter fails

2024-02-23 12:24 UTC, OrKoN requested changes
still fails with webpack

2024-02-26 10:42 UTC, OrKoN approved these changes

2024-02-26 10:42 UTC, merged

2024-02-26 10:46 UTC, Lightning00Blade commented
@jrandolf this need to be marked as a `feat:`