docs(README.md): Update docs to more clearly differentiate between Ch…
puppeteer/puppeteer pull request #1574
Opened 2017-12-11 14:37 UTC by karlwbrown

…romium and Chrome

This patch clarifies the documentation to more clearly note that Puppeteer works with both Chromium (by default)
and Chrome.

Fixes #1516

2017-12-11 20:07 UTC, ebidel requested changes

2017-12-11 20:07 UTC, ebidel commented on README.md
> +See [`this document`](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/chromium_browser_vs_google_chrome.md) for a description
https://www.howtogeek.com/202825/what%E2%80%99s-the-difference-between-chromium-and-chrome/ is a bit newer and isn't specific to Linux.

2017-12-11 20:07 UTC, ebidel commented on docs/api.md
> +  * [Chromium vs Chrome](#chromium-vs-chrome)
I wonder if we need this section in the API docs? It's duplicated in README.

2017-12-11 20:07 UTC, ebidel commented on docs/api.md
> +  - `handleSIGINT` <[boolean]> Close Chromium process on Ctrl-C. Defaults to `true`.
Chromium -> "browser" for these?

2017-12-11 20:27 UTC, karlwbrown commented on README.md
> +See [`this document`](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/chromium_browser_vs_google_chrome.md) for a description
Fair enough, but my thought was, chromium.googlesource.com is an official google page, as opposed to howtogeek, which is maintained by someone random. We could link both perhaps?

2017-12-11 20:28 UTC, karlwbrown commented on docs/api.md
> +  * [Chromium vs Chrome](#chromium-vs-chrome)
I added it because there was already a note about chrome vs chrominum, so I just made it into a section and added a little bit more exposition.

2017-12-11 20:28 UTC, karlwbrown commented on docs/api.md
> +  - `handleSIGINT` <[boolean]> Close Chromium process on Ctrl-C. Defaults to `true`.
sure that seems reasonable.

2017-12-11 23:35 UTC, ebidel commented on docs/api.md
> +  * [Chromium vs Chrome](#chromium-vs-chrome)
Ack

2017-12-11 23:37 UTC, ebidel commented on README.md
> +See [`this document`](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/chromium_browser_vs_google_chrome.md) for a description
I tend to agree with you, but that page is very specific to Linux. It might confuse people.

2017-12-12 17:07 UTC, karlwbrown commented
Made some changes as discussed, please take another look.

2017-12-13 22:39 UTC, ebidel approved these changes

2017-12-15 03:09 UTC, merged