feat(ElementHandle): Model parameter for boundingBox
puppeteer/puppeteer pull request #1618
Opened 2017-12-18 13:27 UTC by schelkun

According to issue https://github.com/GoogleChrome/puppeteer/issues/1357

Now user can specify box model. If model is not specified - `border` will be used.
Method will be more flexible with full model: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-BoxModel

2017-12-18 20:20 UTC, schelkun commented
Nameing is incorrect as I think.
Model should be changed to box. Any comments?

2017-12-19 00:55 UTC, aslushnikov commented
> Naming is incorrect as I think.
> Model should be changed to box. Any comments?

I agree. I'd have the `elementHandle.boxModel()` that returns all of the boxes right away.
```js
const boxModel = await elementHandle.boxModel();
boxModel.content; // box with {x, y, width, height}
boxModel.margin; // the same here and others
boxModel.border;
boxModel.padding;
```

2017-12-19 09:42 UTC, schelkun commented
@aslushnikov in this case we should rewrite all code that use `boundingBox` method. My idea is optional parameter, so method should be working the same way if no args specified.

2017-12-20 05:12 UTC, aslushnikov commented on docs/api.md
> +  - width <[number]> the width of the element in pixels.
How is this different from content width?

2017-12-20 05:12 UTC, aslushnikov commented on lib/ElementHandle.js
>    async boundingBox() {
Can we rename this into `boxModel`? The `boundingBox` was named to match the `getBoundingClientRect` semantics; the new behavior no longer matches it.

2017-12-20 05:12 UTC, aslushnikov commented on lib/ElementHandle.js
> +    const calculatePos = function(quad)  {
nit: `calculateBox` could be a better name

2017-12-20 10:24 UTC, schelkun commented
Oops, conflict. What's wrong? :thinking:

2018-01-08 22:50 UTC, aslushnikov approved these changes

2018-01-08 22:57 UTC, aslushnikov requested changes
Excuse me my confusion.

I just realized that for a rotated element the `boxModel` should be rotated as well. The `boundingBox`, on the other hand, is axis-aligned.

For most purposes, the `boundingBox` is easier and nicer to work with; we should keep it.

The `boxModel` should return quads; but it's unclear  how convenient it is.

2018-01-09 15:10 UTC, schelkun commented
So, this PR was made for changing original `boundingBox`.
This PR is closed and new PR will created with new method.

2018-01-09 15:10 UTC, closed without merging