feat(Page): Add global timeout setting
puppeteer/puppeteer pull request #1728
Opened 2018-01-05 15:20 UTC by raduaron26

References #1514

2018-01-05 15:22 UTC, raduaron26 commented
I signed the CLA.

2018-01-05 19:07 UTC, aslushnikov commented
Can you please eliminate the default 30000 timeout from the NavigatorWatcher?

https://github.com/GoogleChrome/puppeteer/blob/8e9c54a789c9d51f9861053b21565ad21a5ffe6f/lib/NavigatorWatcher.js#L41-L48

I'd do this by passing timeout explicitly to the NavigatorWatcher as one of the arguments in its constructor.

2018-01-07 23:30 UTC, raduaron26 commented
I did it, but the AppVeyor build failed, and I can't figure out why that test failed.

2018-01-09 00:59 UTC, aslushnikov reviewed
@raduaron26 no worries about appveyour, some of our tests are flaky. 

Thank you for working on this. I have a minor comment, other than that it's good to go.

2018-01-09 00:59 UTC, aslushnikov commented on test/test.js
> +    it('should work', async({page, server}) => {
We generally try hard not to reach out to private fields.
Let's drop this test – i think the other one you add is sufficient.

2018-01-09 18:23 UTC, raduaron26 commented
I removed the test. I'm glad I could contribute and thank you too for your help :)

2018-01-09 21:37 UTC, aslushnikov approved these changes

2018-01-09 22:04 UTC, aslushnikov commented on docs/api.md
> +  * [page.setDefaultNavigationTimeout(timeout)](#pagesetdefaultnavigationtimeouttimeout)
So this setting affects 5 methods: `page.goto`, `page.goBack`, `page.goForward`, `page.reload` and `page.waitForNavigation`.
Can you please:
- refer to the methods from the doc of the method, explaining that this method will change defaults for them, and that the default value is 30 seconds
- update documentation for the methods themselves, citing `page.setDefaultNavigationTimeout`.

This should make it more understandable for our clients.

2018-01-09 22:05 UTC, aslushnikov requested changes
@raduaron26 I've just figured there's one last nit for the documentation before this should be merged. Thanks again for taking your time for this

2018-01-10 18:47 UTC, raduaron26 commented
I updated the documentation, let me know if you want me to make any tweaks to what I wrote.

2018-01-10 21:02 UTC, aslushnikov approved these changes
Thank you, this looks good.

2018-01-10 21:04 UTC, merged

2018-02-19 12:35 UTC, stackflows commented
@aslushnikov: This only affects navigation. waitForSelector() etc. should have a similar global "default" setting. Shall I write a feature request for this?

2018-07-02 09:12 UTC, Peta5000 commented
@stackflows Did you write a feature request for this? This feature would be so precious.

2018-11-09 18:15 UTC, spinningarrow commented
@Peta5000 it looks like #1514 is the issue for this but it is closed. I've added a comment there voting to reopen.