Add CA DMV behind-the-wheel appointment example.
puppeteer/puppeteer pull request #229
Opened 2017-08-09 22:16 UTC by a1ph

The script allows you to pick up a certain date for your DMV
behind-the-wheel test appointment.

2017-08-09 22:41 UTC, paulirish commented on examples/ca-dmv-appointment.js
> + * Copyright 2017 Google Inc., PhantomJS Authors All rights reserved.
afaik just google on this header

2017-08-09 22:41 UTC, paulirish commented on examples/ca-dmv-appointment.js
> +    const offices = $('select#officeId option');
is the `$` coming from our commandline API, or is it their copy of jQuery?

2017-08-09 22:41 UTC, paulirish commented on examples/ca-dmv-appointment.js
> +    console.log('Form data seems to be wrong. Please check the form response screenshot.');
love taking a screenshot in the error state. nice

2017-08-09 22:43 UTC, aslushnikov reviewed
Success story! 😏 Would you mind changing a few bits here and there to make it a nice api demo?

2017-08-09 22:43 UTC, aslushnikov commented on examples/ca-dmv-appointment.js
> + * Copyright 2017 Google Inc., PhantomJS Authors All rights reserved.
let's have just google's license here

2017-08-09 22:43 UTC, aslushnikov commented on examples/ca-dmv-appointment.js
> +  await page.evaluate(() => $('form.form-horizontal[id="ApptForm"] input[value="Confirm"]').click());
Should page.click work here? 
```js
page.click('form.form-horizontal[id="ApptForm"] input[value="Confirm"]')
```

2017-08-09 22:43 UTC, aslushnikov commented on examples/ca-dmv-appointment.js
> +async function sleep(timeout) {
can we kill sleeps altogether? they should not be needed

2017-08-09 22:43 UTC, aslushnikov commented on examples/ca-dmv-appointment.js
> +  await page.screenshot({path: 'dmv-filed-form.png'});
Looks like you're interested in a full-page screenshot everywhere.. shall we make it a default? cc @ebidel @paulirish

2017-08-09 23:05 UTC, ebidel requested changes

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +browser.newPage().then(async page => {
to be consistent with the other examples:

```javascript
(async() => {
  const page = await browser.newPage();
  await page.setViewport({width: 600, height: 1200});
  await iterate(page);
  browser.close();
})();
```

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +  // Sumbitting the form
// Submit the form

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +  const officeString = await page.evaluate(() => $('td[data-title="Office"] p').text());
Is jquery on their page? That might be too confusing :) Probably should stick with vanilla:

`document.querySelector('td[data-title="Office"] p').textContent`
`document.querySelector('td[data-title="Appointment"] strong').textContent`

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +async function fillForm(page, location) {
it would be nice to have jsdocs on these functions

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +async function sleep(timeout) {
dont think you need the `async`

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +}
newline

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +const Browser = require('../lib/Browser');
Can we stick all requires at the top?

2017-08-09 23:05 UTC, ebidel commented on examples/ca-dmv-appointment.js
> +const Browser = require('../lib/Browser');
Oh my, we've got 3 flavors of this require in the codebase so far:
```
const {Browser} = require('puppeteer');
const {Browser} = require('..');
const Browser = require('../lib/Browser');
```

Suggest sticking with `const {Browser} = require('puppeteer');` in all the examples. That'll make it easier to cut and paste from the examples.

2017-08-09 23:16 UTC, aslushnikov commented
We feel uncomfortable having this in – let's not add it.

2017-08-09 23:16 UTC, closed without merging

2017-08-10 12:35 UTC, Garbee commented
I think this is a decent example that shows you can pre-populate data in some way (the `FormData`) as well as capture screenshots on error for the developer to view what went wrong. Overall, quite useful for people to have a reference point to know it is possible.

What is the source of the uncomfort with including this? Is there anything that can be done to the example to make it acceptable (beyond all of the existing review on code style.)