Replace headless: false with headless: true
puppeteer/puppeteer pull request #332
Opened 2017-08-17 09:09 UTC by sericaia

I just read the [docs](https://developers.google.com/web/updates/2017/04/headless-chrome):

```js
@param {boolean=} headless True (default) launches Chrome in headless mode.
```

It makes more sense to me to have `headless: true` here as `headless: false` may confuse people

2017-08-17 11:28 UTC, Garbee commented
So this is the *example* code in the README. Associated with the following excerpt:

> Puppeteer launches Chromium in headless mode. To launch a full version of Chromium, set the 'headless' option when creating a browser:

So, this example code is instructing people how to run it with the UX so they can see what is going on. Which is *not* the default behavior which is a true flag for headless mode.

Rather than change the example which then makes it not align with the context of usage. Could a simple comment be added at the end of the line `// default headless mode is 'true'`?

2017-08-17 17:07 UTC, ebidel requested changes

2017-08-17 17:07 UTC, ebidel commented on README.md
>  Puppeteer launches Chromium in [headless mode](https://developers.google.com/web/updates/2017/04/headless-chrome). To launch a full version of Chromium, set the ['headless' option](https://github.com
Think we can help clarify with:

`set the ['headless' option](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) when creating a browser`
->
`use the ['headless: false'](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) option when launching a browser:`

2017-08-17 17:07 UTC, ebidel commented on README.md
> +const browser = await puppeteer.launch({headless: true});
`const browser = await puppeteer.launch({headless: false}); // default is true`

2017-08-20 11:24 UTC, sericaia commented
I agree and did the suggested changes, and CLA was signed.

2017-08-20 19:34 UTC, ebidel approved these changes

2017-08-20 19:40 UTC, merged