refactor: move to flatten protocol
puppeteer/puppeteer pull request #3524
Opened 2018-11-09 05:58 UTC by aslushnikov

DevTools protocol is dropping nested targets and switching to
flatten protocol. This patch adopts the new scheme.

Once this change lands, tip-of-tree Puppeteer will be incompatible
with Chromium below 72.0.3606.0. We'll need to adopt multiple pptr versions approach for [carlo](https://github.com/GoogleChromeLabs/carlo) to make it work nicely.

2018-11-12 18:39 UTC, JoelEinbinder commented on lib/Connection.js
> +  _rawSend(message) {
jsdoc.

2018-11-12 18:39 UTC, JoelEinbinder commented on lib/Connection.js
> +    message = JSON.stringify(Object.assign({}, message, {id}));
Can we not re-use the message variable here? It becomes a bit tricky to follow.

2018-11-12 18:42 UTC, JoelEinbinder approved these changes

2018-11-12 19:11 UTC, JoelEinbinder commented
I still don't think we should land this until flat hits stable.

2018-11-30 00:22 UTC, JoelEinbinder requested changes
undoing my +1

2018-12-05 05:23 UTC, aslushnikov commented
We'll come back to this with 2.0 release.

2018-12-05 05:23 UTC, closed without merging