fix(Navigator): add better network idle definition
puppeteer/puppeteer pull request #38
Opened 2017-06-23 00:53 UTC by patrickhulce

* Changes network idle promise to wait for 2 or fewer network requests for at least idleTime (defaults to 5s) before resolving.
* Add timer cleanup to failure navigation case.
* Add handling of webSocketClosed.
* Ignore unrecognized requestIds to avoid negative inflight requests.
* Fixes default options for Navigator to allow 0

2017-06-23 00:54 UTC, patrickhulce commented
happy to add a test page too just unsure of where, throw a new html file into `test/assets/long-load.html` or something?

2017-06-23 21:28 UTC, aslushnikov requested changes
Thank you for this patch, Patrick!

2017-06-23 21:28 UTC, aslushnikov commented on lib/Navigator.js
> +    client.on('Network.webSocketClosed', event => this._onWebSocketClosed(event));
can we add a websocket test?

2017-06-23 21:28 UTC, aslushnikov commented on lib/Navigator.js
>    async navigate(url, referrer) {
Let's have the following api for page.navigate: 
```js
page.navigate(url, {
    maxTime: 30000 // time in ms
    waitFor: 'networkidle', // employ network idle heuristic. Could be 'onload' as well
    networkIdleTimeout: 1000 , // in case of waitFor = networkIdle, this is the network idle timeout
})
```
let's have the 'waitFor: load' by default

@paulirish how do you feel about these navigation options?

2017-06-23 21:28 UTC, aslushnikov commented on test/test.js
> +      await page.navigate(EMPTY_PAGE, {idleTime: 0});
let's wait for load event by default - it's probably the most basic case,  and it will save us from changes in this file (also, the phantom tests would pass as well)

2017-06-27 02:24 UTC, patrickhulce commented on lib/Navigator.js
>    async navigate(url, referrer) {
done! added two options minTime, and networkIdleInflight, but most shouldn't need to mess with them

2017-06-27 03:13 UTC, aslushnikov requested changes

2017-06-27 03:13 UTC, aslushnikov commented on package.json
> +    "websocket": "^1.0.24"
any chance we can reuse the [ws](https://github.com/websockets/ws) module here? We already depend on it, and it also has a server implementation

2017-06-27 03:13 UTC, aslushnikov commented on test/test.js
> +  fdescribe('Page.navigate', function() {
could you please un-focus the suite?

2017-06-27 03:13 UTC, aslushnikov commented on test/test.js
> +    it('should wait for network idle when requested', SX(async function() {
how long does the test run for? (I'm afraid it is ran for 4 seconds - i wonder if there's a way to have it run faster?)

2017-06-27 03:13 UTC, aslushnikov commented on lib/Navigator.js
> +    this._waitFor = typeof options.waitFor === 'string' ? options.waitFor : 'load';
Could you please also assert here that the value is either 'load' or 'networkidle'?

2017-06-27 03:13 UTC, aslushnikov commented on lib/Navigator.js
> +      // client.on('Network.webSocketClosed', event => this._onWebSocketClosed(event));
shouldn't it be uncommented?

2017-06-27 15:03 UTC, patrickhulce commented on package.json
> +    "websocket": "^1.0.24"
oops, missed that! :)

2017-06-27 15:03 UTC, patrickhulce commented on test/test.js
> +  fdescribe('Page.navigate', function() {
yeah done, premature push

2017-06-27 15:03 UTC, patrickhulce commented on lib/Navigator.js
> +      // client.on('Network.webSocketClosed', event => this._onWebSocketClosed(event));
yeah done, premature push

2017-06-27 16:32 UTC, patrickhulce commented on test/test.js
> +    it('should wait for network idle when requested', SX(async function() {
it should run for 2.5 seconds, wdyt about using something like https://github.com/avajs/ava to try and run these in parallel?

2017-06-27 16:33 UTC, patrickhulce commented on lib/Navigator.js
> +    this._waitFor = typeof options.waitFor === 'string' ? options.waitFor : 'load';
done

2017-06-27 17:25 UTC, aslushnikov commented on test/test.js
> +    it('should wait for network idle when requested', SX(async function() {
> it should run for 2.5 seconds, wdyt about using something like https://github.com/avajs/ava to try and run these in parallel?

Thanks for pointing out the ava project. Indeed, we can harvest great benefits from parallel test running! Right now I think jasmine works good enough for our needs, so I'm hesitant to switch testing framework. But if/when test running becomes a pain, we should consider ava.

I think it would be nice to have tests that run as fast as possible, so I've thought about the case here for a while. I think we can make it run almost instantly without much effort – with the help of server-side request interceptor.

Consider the following scenario:
1. test sets a server-side interceptor for certain urls which just holds on requests without replying
2. test navigates page to html file with `waitFor: 'networkidle'` parameter
3. html file fires 3 fetch requests. These fetch requests are hanging because of server-side request interceptor
4. test makes sure the 'load' event is fired, but navigation is not completed
5. test replies to one of the fetch requests and makes sure navigation finishes

what do you think?

2017-06-27 21:08 UTC, patrickhulce commented on test/test.js
> +    it('should wait for network idle when requested', SX(async function() {
implemented, it should be down to ~400ms now which is just load + 100ms

2017-06-27 22:33 UTC, aslushnikov commented on test/test.js
> +      page.setRequestInterceptor(request => {
ah, i see now why you said that "test seems to be testing itself"! Indeed looks like this!

Sorry about this, I should've been more clear. I actually meant intercepting on the server side, not on the puppeteer side. So, instead of
```js
page.setRequestInterceptor(request => { 
   ...
})
```
it would be
```js
staticServer.setRequestInterceptor(request => {
   ...
})
```

However, this approach works well! We can land the test like this and i'll refactor it later when the staticserver's interception is there.

2017-06-27 22:33 UTC, aslushnikov commented on test/test.js
> +          }, 50);
Why is this setTimeout needed? Why releasing all requests simultaneously wouldn't work?

2017-06-27 23:36 UTC, patrickhulce commented on test/test.js
> +      page.setRequestInterceptor(request => {
Oh I actually had static server interception before we spoke 😆 but thought you wanted it to use the built-in one

2017-06-27 23:37 UTC, patrickhulce commented on test/test.js
> +          }, 50);
it's just way too easy for it to pass without properly waiting for load, there's not enough to non-flakily distinguish waiting for the requests and the 50 ms timeout from the HTML file, open to other ideas

2017-06-27 23:38 UTC, patrickhulce commented on test/test.js
> +      page.setRequestInterceptor(request => {
I honestly don't think there's much a difference in the exercising of meaningful code under test, at least this way the more non-test code is exercised instead of just test code

2017-06-28 00:57 UTC, aslushnikov commented on test/test.js
> +          }, 50);
Let's land the https://github.com/GoogleChrome/puppeteer/pull/46 and move the test over to the waitForRequest() methods of the static server?

2017-06-28 01:19 UTC, aslushnikov approved these changes

2017-06-28 21:39 UTC, merged

2017-06-28 21:39 UTC, aslushnikov commented
lgtm!

2017-10-13 08:25 UTC, pakastin commented
> Maximum amount of inflight requests which are considered "idle".

What does this mean?

2017-10-13 15:56 UTC, patrickhulce commented
@pakastin it means the page can have up to `networkIdleInflight` requests inflight and still be considered "idle". For example when networkIdleInflight=0, it means that the page is not idle until there have been *no* inflight requests for `networkIdleTimeout`ms. When networkIdleInflight=2, it means that the page is not idle until there have been *no more than 2* inflight requests for `networkIdleTimeout`ms. This is useful in dealing with pages that use long polling.

2017-10-13 16:28 UTC, pakastin commented
I mean what is an _inflight_ request.. 🤔 I’m not native English speaker and tried to google it but didn’t understand..

2017-10-13 16:39 UTC, patrickhulce commented
Oh! An inflight request is a network request that has been started but is not yet finished, i.e. the browser has requested the asset from the server but is either waiting for a response or still downloading the content.

2017-10-13 17:04 UTC, pakastin commented
Ok, that was simpler than I thought 😆

Thank you for making such a great tool, I’m so happy with it! 👌