Basic input
puppeteer/puppeteer pull request #45
Opened 2017-06-27 22:50 UTC by JoelEinbinder

#43 
Adds
```javascript
.click(selector)
.focus(selector)
.type(text)
```

2017-06-27 23:05 UTC, aslushnikov requested changes

2017-06-27 23:05 UTC, aslushnikov commented on test/assets/input/textarea.html
> +    <title>Button test</title>
text area test?

2017-06-27 23:05 UTC, aslushnikov commented on lib/Page.js
> +    let documentNode = await this._client.send('DOM.getDocument', {
we should query for the document only once in the very beginning

2017-06-27 23:05 UTC, aslushnikov commented on lib/Page.js
> +    let x = Math.round((boxModel[0] + boxModel[0]) / 2);
this feels like an error

2017-06-27 23:05 UTC, aslushnikov commented on lib/Page.js
> +    await this._client.send('Input.dispatchMouseEvent', {
you can await only the last one due to the serial nature of the protocol

2017-06-27 23:05 UTC, aslushnikov commented on lib/Page.js
> +    await this.evaluate(selector => {
let's use DOM.querySelector and DOM.focus

2017-06-27 23:05 UTC, aslushnikov commented on lib/Page.js
> +      await this._client.send('Input.dispatchKeyEvent', {
you'd probably speed this up considerably if you were to wait only for the *very* last one

2017-06-27 23:05 UTC, aslushnikov commented on test/assets/input/textarea.html
> +      window.result = "";
''

2017-06-27 23:51 UTC, JoelEinbinder commented on test/assets/input/textarea.html
> +      window.result = "";
Done.

2017-06-27 23:51 UTC, JoelEinbinder commented on lib/Page.js
> +    let x = Math.round((boxModel[0] + boxModel[0]) / 2);
Done.

2017-06-28 00:24 UTC, JoelEinbinder commented on test/assets/input/textarea.html
> +    <title>Button test</title>
Done.

2017-06-28 00:24 UTC, JoelEinbinder commented on lib/Page.js
> +    await this.evaluate(selector => {
Done

2017-06-28 00:24 UTC, JoelEinbinder commented on lib/Page.js
> +      await this._client.send('Input.dispatchKeyEvent', {
Done.

2017-06-28 01:09 UTC, aslushnikov approved these changes

2017-06-28 01:27 UTC, merged