fix(Launcher): launcher.launch() should pass 'timeout' option to browser.waitForTimeout
puppeteer/puppeteer pull request #5180
Opened 2019-11-18 16:46 UTC by ishmal

Addresses https://github.com/GoogleChrome/puppeteer/issues/4782

2019-11-18 17:03 UTC, ishmal commented
@googlebot I fixed it.

2019-11-18 17:14 UTC, bobpearson commented
@googlebot I consent.

2019-11-28 11:28 UTC, kblok commented on test/launcher.spec.js
> +        Browser.prototype.waitForTarget = async function(predicate, options) {
The pattern we use to test timeout is setting the timeout to 1 and expecting to fail. [See](https://github.com/puppeteer/puppeteer/blob/eddb23b52175a3dad8cec4a5e9b3c13e58f6f144/test/page.spec.js#L501)

2021-09-11 10:08 UTC, jschfflr requested changes
@ishmal Thanks for your contribution! Could you address @kblok's comment and resolve the merge conflicts? Happy to get this landed :)

2021-09-23 16:21 UTC, jschfflr commented
Closing this in favor of https://github.com/puppeteer/puppeteer/pull/7596.

2021-09-23 16:21 UTC, closed without merging