feat: id option for addScriptTag
puppeteer/puppeteer pull request #5477
Opened 2020-03-04 18:39 UTC by noam3127

Resolves #5166

2021-09-11 10:21 UTC, jschfflr requested changes
@noam3127 Thanks for your contribution! Could you resolve the merge conflicts?
Happy to get this landed :)

2021-09-13 13:58 UTC, noam3127 commented
Look like something got messed up when rebasing. Considering starting from scratch and opening a new PR from a fresh branch.

2021-09-13 14:47 UTC, noam3127 commented
Fixed the conflicts. @jschfflr let me know if I can do anything else. Thanks.

2021-09-14 18:43 UTC, jschfflr approved these changes

2021-09-14 21:02 UTC, merged