Fix for #5034
puppeteer/puppeteer pull request #5601
Opened 2020-04-07 11:59 UTC by plato79

This fixes the errors when installing, although environment variable to skip download still should be used like this:
`setenv PUPPETEER_SKIP_DOWNLOAD true`

2020-04-09 06:18 UTC, plato79 commented
@googlebot I signed it!

2020-04-09 10:12 UTC, plato79 commented
Could somebody check this? This fixes https://github.com/puppeteer/puppeteer/issues/5034 . Although it stucks for something not related with this it seems.

2020-11-15 21:23 UTC, 0mp commented
It would be great if we could have it merged. @plato79, do you still have time to resolve the conflicts perhaps?

2021-09-11 10:26 UTC, jschfflr commented
@mathiasbynens Not sure if supporting `freebsd` is something we want to officially commit to doing - could you take a look and resolve this accordingly?

2021-09-19 22:31 UTC, 0mp commented
> @mathiasbynens Not sure if supporting `freebsd` is something we want to officially commit to doing - could you take a look and resolve this accordingly?

Thanks for working on this PR. It's much appreciated. 😃

2021-09-20 05:17 UTC, mathiasbynens requested changes
I believe this patch affects the public `puppeteer.createBrowserFetcher` API and its `platform` option but it doesn't document the changes.
However, it's better not to change this API and stick to the current list of user-exposed `platform`s (`"linux"|"mac"|"win32"|"win64"`) since those are the ones we test and provide support for.

It looks like this patch is just using the Linux URLs and codepaths for `freebsd` anyway — so can we just treat `freebsd` as an alias to `linux`? That would avoid these issues.

2021-09-20 05:17 UTC, mathiasbynens commented on src/BrowserFetcher.js
> +      else if (this._platform === 'freebsd')
Can we merge this with the `else if (this._platform === 'linux')` above?

2021-09-20 05:17 UTC, mathiasbynens commented on src/BrowserFetcher.js
> +    if (platform === 'freebsd')
Can we merge this with the `if (platform === 'linux')` above?

2021-09-20 05:17 UTC, mathiasbynens commented on src/BrowserFetcher.js
> +      else if (this._platform === 'freebsd')
Merge this with the check above

2021-09-20 05:17 UTC, mathiasbynens commented on src/BrowserFetcher.js
> +    freebsd: '%s/chromium-browser-snapshots/Linux_x64/%d/%s.zip',
This and the Firefox URL below are the same ones as for Linux? In that case let's simplify the patch by removing this line and line 42 and treating `'freebsd'` as equivalent to `'linux'`.

That way this change also doesn't impact the public `puppeteer.createBrowserFetcher` API.

2021-09-20 08:14 UTC, plato79 commented
> I believe this patch affects the public `puppeteer.createBrowserFetcher` API and its `platform` option but it doesn't document the changes.
> However, it's better not to change this API and stick to the current list of user-exposed `platform`s (`"linux"|"mac"|"win32"|"win64"`) since those are the ones we test and provide support for.
> 
> It looks like this patch is just using the Linux URLs and codepaths for `freebsd` anyway — so can we just treat `freebsd` as an alias to `linux`? That would avoid these issues.

The thing is puppeteer checks for the system and if it's freebsd it just doesn't work at all.. The links doesn't matter because chromium should be installed manually anyway on freebsd ( there is no official support ). You could also use dummy download links or no download links at all.. So, as I said in the first post you need to use `setenv PUPPETEER_SKIP_DOWNLOAD true` first to avoid downloading part.

2021-09-21 08:33 UTC, jschfflr commented
Not sure if I understand you correctly: For FreeBSD, the normal linux build of Chromium doesn't work. That's why you `setenv PUPPETEER_SKIP_DOWNLOAD true` to prevent Puppeteer from downloading something and you instead install it manually. In which situation would the `BrowserFetcher` be used then?

2021-09-22 10:39 UTC, plato79 commented
> Not sure if I understand you correctly: For FreeBSD, the normal linux build of Chromium doesn't work. That's why you `setenv PUPPETEER_SKIP_DOWNLOAD true` to prevent Puppeteer from downloading something and you instead install it manually. In which situation would the `BrowserFetcher` be used then?

Yes, normal linux build doesn't work but there are custom FreeBSD builds of chromium exists which you need to compile yourself.. The thing is puppeteer still searches for freebsd in BrowserFetcher if the system is FreeBSD. This is just a dummy selection to prevent runtime errors.

2021-09-23 08:04 UTC, jschfflr commented
@plato79 My expectation would be that we don't ever get into a situation where we'd run `BrowserFetcher` if `PUPPETEER_SKIP_DOWNLOAD` is set. Could you maybe share a quick snippet to reproduce the problem?

2021-09-29 15:32 UTC, jschfflr commented
@plato79 Gentle ping :)

2021-10-04 07:44 UTC, jschfflr commented
@plato79 I'm going to close this for now because it's not actionable for me but please feel free to reopen if you found out why the browser fetcher is still invoked even though `PUPPETEER_SKIP_DOWNLOAD ` was set!

2021-10-04 07:44 UTC, closed without merging