feat(launcher): fix installation error on Apple M1 chips
puppeteer/puppeteer pull request #7099
Opened 2021-04-18 12:36 UTC by marvinhagemeister

The previous logic assumed that an arm64 arch is only available in
Linux. WIth Apple's arm64 M1 Chip this assumption isn't true anymore.

Currently there are no official MacOS arm64 chromium builds available,
but we can make use of the excellent Rosetta feature in MacOS that
allows us to run x86 binaries on M1.

Once native MacOS arm64 chromium builds are available we should switch to
those.

Fixes #6622

2021-04-19 06:58 UTC, mathiasbynens approved these changes

2021-04-19 06:59 UTC, mathiasbynens commented on src/node/BrowserFetcher.ts
> +    // chromium builds are available
```suggestion
    // Use Intel x86 builds on Apple M1 until native macOS arm64
    // Chromium builds are available.
```

2021-04-19 06:59 UTC, mathiasbynens commented on src/node/Launcher.ts
> +      // chromium builds are available
```suggestion
    // Use Intel x86 builds on Apple M1 until native macOS arm64
    // Chromium builds are available.
```

2021-04-19 06:59 UTC, mathiasbynens commented on src/node/install.ts
> +      // chromium builds are available
```suggestion
    // Use Intel x86 builds on Apple M1 until native macOS arm64
    // Chromium builds are available.
```

2021-04-19 07:00 UTC, merged

2021-04-21 15:18 UTC, l198881 requested changes
.