build: allow to customize tmpdir
puppeteer/puppeteer pull request #7243
Opened 2021-05-16 22:47 UTC by Kikobeats

Hello,

This change allows customizing the directory for temporary files, setting up the current behavior as default.

2021-05-16 22:50 UTC, Kikobeats commented
hum checks are failing for a non related thing.

2021-05-17 06:57 UTC, mathiasbynens requested changes
The option is named `tmpdir` but it should be `tmpDir` to match the casing convention.

If we want to do this then introducing an [environment variable](https://github.com/puppeteer/puppeteer/blob/v9.1.1/docs/api.md#environment-variables) like `PUPPETEER_TMP_DIR` seems like a cleaner option.

The patch would also need to include a test and the relevant changes to documentation. WDYT?

2021-05-17 07:44 UTC, Kikobeats commented
ops, fixed the camel case naming 🙂

I'm not sure about `PUPPETEER_TMP_DIR` because it's limiting the possibility to use a function where the path can change over time, rather than a static string.

2021-05-17 08:04 UTC, mathiasbynens commented
> I'm not sure about `PUPPETEER_TMP_DIR` because it's limiting the possibility to use a function where the path can change over time, rather than a static string.

If the path changes over time and your code knows about it, can't you have it update the `PUPPETEER_TMP_DIR` env var accordingly?

2021-05-17 09:07 UTC, Kikobeats commented
you're right; I'm assuming `os.tmpdir()` will return a different path every time, but it looks like constant value:

<img width="415" alt="Screen Shot 2021-05-17 at 11 06 05" src="https://user-images.githubusercontent.com/2096101/118463294-e633c400-b6ff-11eb-82e9-bba9e6d91e74.png">

let me do the code changes for a new environment variable 🙂

2021-05-18 14:36 UTC, Kikobeats commented
@mathiasbynens done at https://github.com/puppeteer/puppeteer/pull/7243/commits/083ea5ff7e8f6a51b16db9699e237864961c9eaa

Do you think it could be moved into a common, so it just could be declared once?

2021-06-04 14:00 UTC, Kikobeats commented
@mathiasbynens Can I do something to move this PR forward? 🙂

2021-06-15 11:34 UTC, mathiasbynens commented
The diff seems to include lots of unrelated changes. Could you please check?

2021-06-15 13:22 UTC, Kikobeats commented
@mathiasbynens updated 👍

2021-06-15 13:48 UTC, mathiasbynens commented on src/node/Launcher.ts
> +const tmpDir = () => process.env.PUPPETEER_TMP_DIR || os.tmpdir()
Could you please fix the lint errors?

2021-06-15 14:51 UTC, Kikobeats commented
@mathiasbynens all green now 🙂

2021-06-15 14:58 UTC, mathiasbynens commented on experimental/puppeteer-firefox/lib/Launcher.js
> +const FIREFOX_PROFILE_PATH = path.join(tmpDir(),'puppeteer_firefox_profile-');
```suggestion
const FIREFOX_PROFILE_PATH = path.join(tmpDir(), 'puppeteer_firefox_profile-');
```

2021-06-15 14:58 UTC, mathiasbynens commented on docs/api.md
> +- `PUPPETEER_TMP_DIR` - defines the directory to be used by Puppeteer for creating temporary files. It's [os.tmpdir](https://nodejs.org/api/os.html#os_os_tmpdir) by default.
```suggestion
- `PUPPETEER_TMP_DIR` - defines the directory to be used by Puppeteer for creating temporary files. Defaults to [`os.tmpdir()`](https://nodejs.org/api/os.html#os_os_tmpdir).
```

2021-06-16 09:10 UTC, Kikobeats commented
@mathiasbynens I think now can be merged

2021-09-11 07:48 UTC, jschfflr requested changes
Could you maybe move the implementation of `const tmpDir = () => process.env.PUPPETEER_TMP_DIR || os.tmpdir();` into a separate file like `helpers.ts` or something similar to reduce code duplication?

2021-09-12 20:42 UTC, Kikobeats commented
> Could you maybe move the implementation of `const tmpDir = () => process.env.PUPPETEER_TMP_DIR || os.tmpdir();` into a separate file like `helpers.ts` or something similar to reduce code duplication?

I want to do that, `experimental/puppeteer-firefox/lib/Launcher.js` is CJS and `src/node/Launcher.ts` is ESM.

I guess I can't just create a file that can be loaded on both parts; am I wrong?

2021-09-13 09:20 UTC, jschfflr commented
> > Could you maybe move the implementation of `const tmpDir = () => process.env.PUPPETEER_TMP_DIR || os.tmpdir();` into a separate file like `helpers.ts` or something similar to reduce code duplication?
> 
> I want to do that, `experimental/puppeteer-firefox/lib/Launcher.js` is CJS and `src/node/Launcher.ts` is ESM.
> 
> I guess I can't just create a file that can be loaded on both parts; am I wrong?

Ah sorry, I didn't see that one is for Firefox and one in src. In this case, I think this change looks good!

2021-09-13 09:20 UTC, jschfflr approved these changes

2021-09-21 22:37 UTC, Kikobeats commented
@jschfflr @mathiasbynens any chance to merge this? it's already approved and tests pass on green 🙂

2021-09-22 08:56 UTC, mathiasbynens approved these changes

2021-09-23 07:26 UTC, merged