$ and $$ as shortcuts for querySelector and querySelectorAll
puppeteer/puppeteer pull request #75
Opened 2017-07-12 22:23 UTC by JoelEinbinder

This version of the patch uses `document.querySelector` instead of `DOM.querySelector`

2017-07-12 22:58 UTC, pavelfeldman commented on lib/Page.js
> +  async _querySelectorAll(selector) {
Why do we need these?

2017-07-14 01:33 UTC, aslushnikov commented on docs/api.md
> +- `...args` <[Array]<[string]>> Arguments to pass to `fun`
in `page.evaluate`, this is documented with type `<...[string]>`. Not sure which one is better, but let's be consistent

2017-07-14 01:33 UTC, aslushnikov commented on lib/FrameManager.js
>    async _evaluateOnFrame(frame, fun, ...args) {
let's inline _evaluateOnFrame into Frame.evaluate

2017-07-14 01:33 UTC, aslushnikov commented on lib/FrameManager.js
> +  async _evaluateStringOnFrame(frame, expression) {
and rename this into `_evaluateOnFrame`

2017-07-14 08:26 UTC, JoelEinbinder commented on lib/FrameManager.js
> +  async _evaluateStringOnFrame(frame, expression) {
Done.

2017-07-14 08:26 UTC, JoelEinbinder commented on lib/FrameManager.js
>    async _evaluateOnFrame(frame, fun, ...args) {
Done.

2017-07-14 08:26 UTC, JoelEinbinder commented on docs/api.md
> +- `...args` <[Array]<[string]>> Arguments to pass to `fun`
Done.

2017-07-14 16:31 UTC, aslushnikov commented
Could you please rebaseline atop of master?
Other then that, lgtm!

2017-07-14 16:31 UTC, aslushnikov commented on test/doclint/MDBuilder.js
> +    const methodRegex = /^(\w+)\.([\w$]+)\((.*)\)$/;
could you please add a doclint test for this

2017-07-14 17:55 UTC, JoelEinbinder commented
Rebased and added a test.

2017-07-14 18:36 UTC, aslushnikov commented on lib/FrameManager.js
> +    return helper.serializeRemoteObjet(this._client, remoteObject);
nit: there's a typo in serializeRemoteObje**C**t

It also looks like this helper method is not needed at all and we can keep it inlined.

2017-07-14 19:18 UTC, pavelfeldman commented
How do I use it?

2017-07-14 19:28 UTC, paulirish requested changes
i have a few suggestions for clarity of the docs.
i expect these to be pretty primary methods, so they can use some love.

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +- `selector` <[string]> Query selector to be run on the page
> A selector to be matched in the page

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluated with first element matching `selector`
Generally I see a lot more `fn` or even `func` than `fun` which is basically 🎉 .

Somewhat separately, I think we should start calling out functions that are evaluated clientside.. like `clientsideFunction`

So i'd go with 

```md
 - `fn` <[clientsideFunction<[Element]>]> Function to be evaluated in-page with the matched element`
```

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +
lets add an example?

```js
const outerhtml = await page.$('#box', e => e.outerHTML);
```

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +- `selector` <[string]> Query selector to be run on the page
> A selector to be matched in the page

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluted for every element matching `selector`.
```md
- `mapFn` <[clientsideFunction<[Element]>]> Function to be evaluated in-page for every matching element.
```

2017-07-14 19:28 UTC, paulirish commented on docs/api.md
> +
Example:

```js
const headings = await page.$$('h1,h2,h3,h4', el => el.innerText);
for (const heading of headings) console.log(heading);
```

2017-07-14 19:45 UTC, aslushnikov commented
@JoelEinbinder let's add examples to the documentation!

@pavelfeldman:
To get inner HTML of the page (as requested in https://github.com/GoogleChrome/puppeteer/issues/78):
```js
const html = await page.$('body', body => body.innerHTML);
```
To get a bounding box:
```js
const box = await page.$('#button', button => {
  const box = button.getBoundingClientRect();
  return {x: box.left, y: box.top};
});
```
To get contents of all `h3` headers:
```js
const headers = await page.$$('h3', h => h.textContent);
```
To draw borders around all elements:
```js
await page.$$('*', e => {
  e.style.setProperty('border', '1px solid blue');
});
```

2017-07-14 19:51 UTC, aslushnikov commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluated with first element matching `selector`
Good call. Let's do this in a separate patch throughout the doc. The change would also require js changes to please doclint.

2017-07-14 20:55 UTC, aslushnikov commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluated with first element matching `selector`
As discussed offline, named them all `pageFunction` throughout the doc in 
76415e1be537e8d56960ddd985c487a948647cbc

2017-07-14 23:29 UTC, JoelEinbinder commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluted for every element matching `selector`.
We are calling it pageFunction now. I'll fix this up in another patch that explains how our functions are executed client side.

2017-07-14 23:29 UTC, JoelEinbinder commented on docs/api.md
> +- `selector` <[string]> Query selector to be run on the page
Done.

2017-07-14 23:29 UTC, JoelEinbinder commented on docs/api.md
> +
Done.

2017-07-14 23:29 UTC, JoelEinbinder commented on docs/api.md
> +- `fun` <[function<[Element]>]> Function to be evaluated with first element matching `selector`
Done.

2017-07-14 23:29 UTC, JoelEinbinder commented on docs/api.md
> +- `selector` <[string]> Query selector to be run on the page
Done.

2017-07-17 23:31 UTC, JoelEinbinder commented
@paulirish I have a scary red X (requested changes) from you. What do I have to do to get rid of it?

2017-07-18 01:45 UTC, paulirish approved these changes
lgtm minus spelling nit.

2017-07-18 01:45 UTC, paulirish commented on lib/helper.js
> +  static async serializeRemoteObjet(client, remoteObject) {
still have this typo. serializeRemoteObjet => serializeRemoteObject

2017-07-18 01:52 UTC, JoelEinbinder commented on lib/helper.js
> +  static async serializeRemoteObjet(client, remoteObject) {
This was merge problem. Whole method doesn't exist anymore.

2017-07-18 01:56 UTC, merged