Add webp to screenshot options
puppeteer/puppeteer pull request #7565
Opened 2021-09-13 19:50 UTC by jonchurch

closes: #5348

Wrote this as a proof of concept, it creates webp successfully. Happy to take any help getting this mergeable. 

I'd upload a webp here but github doesn't support them!

2021-09-13 19:55 UTC, jonchurch commented
@googlebot I signed it!

2021-09-14 12:45 UTC, jschfflr requested changes
Thanks for your contribution! The change looks good from a technical point of view but it would be great if you could also update the documentation (`docs/api.md`) and add a unit test (see `screenshot.spec.ts`). Thanks!

2021-09-14 12:59 UTC, jschfflr requested changes

2021-09-14 12:59 UTC, jschfflr commented on src/common/Page.ts
> +  type?: 'png' | 'jpeg' | 'webp';
Can you use `Protocol.Page.CaptureScreenshotRequestFormat` here?

2021-09-14 12:59 UTC, jschfflr commented on src/common/Page.ts
>    private async _screenshotTask(
Not sure how `shouldSetDefaultBackground` should behave for `webp` - could you check that?

2021-09-14 12:59 UTC, jschfflr commented on src/common/Page.ts
> +        options.type === 'png' ||
Is it somehow possible to have TypeScript make sure that this check is extensive?

2021-09-21 14:00 UTC, jschfflr commented
@googlebot I consent.

2021-09-21 14:11 UTC, jschfflr commented
@jonchurch I already went ahead and addressed the outstanding comments to get this into the next release :)

2021-09-21 14:11 UTC, jschfflr approved these changes

2021-09-21 14:26 UTC, merged

2021-09-23 22:40 UTC, jonchurch commented
@jschfflr Yay! Thank you for getting this over the finish line 🥇

2021-09-28 09:01 UTC, jschfflr commented
Sure, happy to help!

2026-01-09 14:21 UTC, cezary13k commented
> zamyka : #5348
> 
> Nie jestem pewien od kiedy, ale webp jest obecnie dostępną opcją [`Page.captureScreenshot`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot).
> 
> Wystarczy pozwolić użytkownikom przejść `type: "webp"`.
> 
> Po wprowadzeniu wspomnianej zmiany umożliwiającej opcjonalne przesyłanie protokołu webp, ten kod pomyślnie tworzy zrzuty ekranu webp, używając `type: "webp"`albo `.webp`rozszerzenia ze ścieżki pliku.
> 
> ```js
> const puppeteer = require('puppeteer')
> 
> async function run() {
> const browser = await puppeteer.launch()
>   const page = await browser.newPage()
>   await page.setViewport({ width: 1280, height: 800 })
>   await page.goto('https://www.nytimes.com/')
>   await page.screenshot({ path: `${__dirname}/nytimes.webp`, fullPage: true, type: 'webp'})
>   await page.screenshot({ path: `${__dirname}/nytimes_alt.webp`, fullPage: true,})
>   await browser.close()
> }
> 
> run().then(() => console.log('done')).catch(console.log)
> ```
> 
> Chętnie przyjmę każdą pomoc w doprowadzeniu tej funkcjonalności do scalania, np. w pisaniu testów.
> 
> Chciałbym wgrać plik webp tutaj, ale github go nie obsługuje!