fix: Inherit browser-level proxy settings from incognito context
puppeteer/puppeteer pull request #7770
Opened 2021-11-11 19:11 UTC by jimmydief

**What kind of change does this PR introduce?**

This fixes #7589 which was a regression caused by #7516 and released in 10.4.0. It closes #7677 which fixed part of the issue but did not cover the proxy bypass list and also did not include tests.

**Did you add tests for your changes?**

Yes.

**If relevant, did you update the documentation?**

N/A

**Summary**

Browser-level proxy settings are now once again respected when creating new incognito browser contexts. Browser-level settings can be overridden at the context level. Tests were added for request proxy behavior in general.

**Does this PR introduce a breaking change?**

Nope.

**Other information**

N/A

2021-11-11 19:16 UTC, jimmydief commented on src/common/Browser.ts
> +    const { proxyServer, proxyBypassList } = options;
Omitting the defaults here causes the browser-level settings to be respected if these aren't provided.

2021-11-11 19:16 UTC, jimmydief commented on test/proxy.spec.ts
> +          const proxyRequest = http.request(
Creating a simple proxy server which forwards requests on to the `TestServer`.

2021-11-12 11:42 UTC, iJoris commented
You are missing the cla
https://github.com/puppeteer/puppeteer/blob/7c0a7b92cf98033425b78e1e7a96bb440a636123/CONTRIBUTING.md#contributor-license-agreement

2021-11-15 17:57 UTC, jimmydief commented
> You are missing the cla https://github.com/puppeteer/puppeteer/blob/7c0a7b92cf98033425b78e1e7a96bb440a636123/CONTRIBUTING.md#contributor-license-agreement

<img width="719" alt="Screen Shot 2021-11-15 at 9 55 58 AM" src="https://user-images.githubusercontent.com/4480230/141830839-3737379e-b302-4670-ab79-50b200d92341.png">

Signed it after opening the PR, seems like updating the status check might require some manual step.

2021-12-06 17:45 UTC, Momotoculteur commented
Hello guys :) 

Any news from this PR ? I need it for my project, i cannot upgrade anymore then my pptr version.

Thank in advance,
Bastien

2022-01-12 11:28 UTC, iJoris approved these changes

2022-02-14 17:20 UTC, Niek commented
Ping @OrKoN @nschonni

2022-02-15 12:23 UTC, OrKoN requested changes
I think the new tests will be failing in Firefox as expected. Could you please add `itFailsFirefox` instead of `it` for those tests?

2022-02-23 21:15 UTC, jimmydief commented
@OrKoN The test failure on Windows actually seems to be pointing out the issue reported in #7873, #7719, and #7698. I put it behind `itFailsWindows` for now and left a comment referring to those issues.

2022-02-23 22:40 UTC, iJoris commented
@jimmydief, closed that issue already. 

If you need testing on windows, hit me up.

2022-02-23 23:27 UTC, jimmydief commented
> @jimmydief, closed that issue already.
> 
> If you need testing on windows, hit me up.

@iJoris Gotcha, thanks. The only test that was failing was related to `createIncognitoBrowserContext` with the `proxyServer` argument provided. Could you confirm whether the example from #7698 fails on your Windows machine?

2022-02-24 09:18 UTC, iJoris commented
> > @jimmydief, closed that issue already.
> > If you need testing on windows, hit me up.
> 
> @iJoris Gotcha, thanks. The only test that was failing was related to `createIncognitoBrowserContext` with the `proxyServer` argument provided. Could you confirm whether the example from #7698 fails on your Windows machine?
Hi,

I can confirm that the proxyserver and an createIncognitoBrowserContext does not work after 10.2. Seems that the proxyServer gets ignored in an incognitoBrowserContext.

I thought that this PR would resolve this issue tho? Otherwise I create my own issue.
`(async () => {
const browser = await puppeteer.launch({
    args: [
        "--proxy-server=" + "http://127.0.0.1:2991"
    ],
    headless: false
});

const context = await browser.createIncognitoBrowserContext();

const page = await context.newPage();

await page.goto('https://www.whatismyip.org/');

await new Promise(() => {
    setTimeout(() => {
      //resolve();
    }, 1000000);
  });
})();`

2022-03-03 13:24 UTC, OrKoN approved these changes

2022-03-07 09:51 UTC, iJoris commented
Ping @nschonni @jrandolf

2022-03-07 10:12 UTC, merged