fix(page): Page.createIsolatedWorld error catching has been added
puppeteer/puppeteer pull request #7848
Opened 2021-12-15 13:30 UTC by DimaShustal

**What kind of change does this PR introduce?**
Bug fix

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Not relevant

**Summary**
When navigating, frames are destroyed and sending events leads to an error that crashes the whole process. This error was mentioned [here](https://github.com/puppeteer/puppeteer/pull/4707). Error example:
```
ProtocolError: Protocol error (Page.createIsolatedWorld): No frame for given id found
at /.../node_modules/puppeteer/src/common/Connection.ts:300:16
at new Promise (<anonymous>)
at CDPSession.send (/.../node_modules/puppeteer/src/common/Connection.ts:296:12)
at /.../node_modules/puppeteer/src/common/FrameManager.ts:397:19
at Array.map (<anonymous>)
at FrameManager._ensureIsolatedWorld (/.../node_modules/puppeteer/src/common/FrameManager.ts:396:10)
at async Promise.all (index 1)
at async FrameManager.initialize (/.../node_modules/puppeteer/src/common/FrameManager.ts:143:7)
at async FrameManager._onAttachedToTarget (/.../node_modules/puppeteer/src/common/FrameManager.ts:262:5) {
originalMessage: 'No frame for given id found'
}
```

**Does this PR introduce a breaking change?**
As I can see there is no breaking change

2021-12-29 16:05 UTC, eemelipa commented on src/common/FrameManager.ts
> +          }).catch(console.error)
Earlier this was 

```suggestion
          }).catch(debugError)
```

imported with `import {debugError} from './helper';`. Should it be the debugError instead?

(For some reason it got removed in https://github.com/puppeteer/puppeteer/commit/4d9dc8c0e613f22d4cdf237e8bd0b0da3c588edb)

2021-12-30 07:45 UTC, eemelipa commented on src/common/FrameManager.ts
> +          }).catch(console.error)
👍 

Looks good now

2021-12-30 07:52 UTC, eemelipa commented
LGTM

I tried the fix in my use case and it seemed to work as expected

Someone from Puppeteer team should give their blessing as well. I don't know all the implications of the change, and why it broke now. I believe the catch clause hasn't been there for a few puppeteer releases so some other change has made this issue surface again

2021-12-30 07:54 UTC, eemelipa approved these changes
LGTM

I tried the fix in my use case and it seemed to work as expected

Someone from Puppeteer team should give their blessing as well. I don't know all the implications of the change, and why it broke now. I believe the catch clause hasn't been there for a few puppeteer releases so some other change has made this issue surface again (e.g. with puppeteer 11.0.0 it wasn't there but v11 worked ok for me)

2022-02-17 11:22 UTC, OrKoN commented
Hey, thanks for the PR. Could you please sign a CLA and rebase (with code style fixes `npm run eslint-fix`) to get this landed?

2022-02-17 11:23 UTC, OrKoN commented
Didn't mean to close :D

2022-02-17 16:02 UTC, OrKoN requested changes
marking as requiring changes (see my previous comment)

2022-02-23 14:54 UTC, DimaShustal commented
I will update PR tomorrow

2022-03-01 23:20 UTC, dmyerscough commented
When will this change make it into Puppeteer?

2022-03-02 12:03 UTC, OrKoN approved these changes

2022-03-02 12:03 UTC, merged