fix: check lifecycle comp. on same page navigation
puppeteer/puppeteer pull request #8348
Opened 2022-05-13 14:58 UTC by jrandolf

2022-05-16 06:04 UTC, OrKoN requested changes
Could you please add the details about what issue is this fixing and why the fix is correct?

2022-05-17 06:01 UTC, OrKoN commented on src/common/FrameManager.ts
> +    this.emit(FrameManagerEmittedEvents.LifecycleEvent, frame);
why do we emit a lifecycle event?

2022-05-17 06:02 UTC, OrKoN commented on test/frame.spec.ts
> +    it('should support lazy frames', async () => {
let's add a similar test to the OOPIF spec

2022-05-17 06:02 UTC, OrKoN commented on test/frame.spec.ts
> +      expect(frames[frames.length - 1]._hasStartedLoading).toBeFalsy();
should we check that the value is true for the rest of the frames?

2022-05-17 06:04 UTC, OrKoN commented on test/frame.spec.ts
> +    it('should support lazy frames', async () => {
probably needs `itFailsFirefox`

2022-05-17 10:00 UTC, OrKoN commented on test/frame.spec.ts
> +      expect(frames.length).toBe(3);
nit: what about the following instead of lines 288 - 293:

```
expect(frames.map(f => f._hasStartedLoading)).toEqual([true, true, false]);
```

2022-05-17 10:05 UTC, jrandolf commented on test/frame.spec.ts
> +      expect(frames.length).toBe(3);
Done; the previous approach was used because it's slightly more robust.

2022-05-17 10:14 UTC, OrKoN approved these changes
LGTM thanks!

2022-05-17 12:15 UTC, merged