fix: recompile before funit and unit commands
puppeteer/puppeteer pull request #8363
Opened 2022-05-18 11:33 UTC by OrKoN

Running only tsc-cjs does not seem sufficient for rebuilding
the project after the compat layer for ESM was introduced.
Let's run `tsc` instead although it's somewhat slower.

Issues: #8362

cc @whimboo

2022-05-18 11:34 UTC, jrandolf approved these changes

2022-05-18 11:35 UTC, jrandolf-google requested changes
Could we run `npm run build` instead? Because the `package.json` for the es modules are not generated with just `npm run tsc`.

2022-05-18 11:37 UTC, OrKoN commented
I don't think we need esm modules and dts for the tests though. I am actually thinking if `tsc-compat-cjs` is enough (so that running tests is not super slow).

2022-05-18 11:44 UTC, jrandolf approved these changes

2022-05-18 11:46 UTC, jrandolf commented
> I don't think we need esm modules and dts for the tests though. I am actually thinking if `tsc-compat-cjs` is enough (so that running tests is not super slow).

My concern was that node may not run because it may see ES modules even when they aren't used and complain.

2022-05-18 12:23 UTC, OrKoN commented
>>I don't think we need esm modules and dts for the tests though. I am actually thinking if tsc-compat-cjs is enough (so that running tests is not super slow).

>My concern was that node may not run because it may see ES modules even when they aren't used and complain

Good point! Let me try with `tsc-compat-cjs` I think the clean up of the lib folder causes failures in the jobs.

2022-05-19 09:15 UTC, merged

2022-05-19 11:34 UTC, whimboo commented
Thanks for the fix @OrKoN!