fix(Target): target interceptor is not async
puppeteer/puppeteer pull request #9430
Opened 2022-12-16 18:45 UTC by kblok

I found that the only call to `addTargetInterceptor` passes `onAttachedToTarget` and is not async.
I also found a typo 🤓

2022-12-17 12:06 UTC, OrKoN requested changes
Thanks for the PR but it is not async on purpose. While the target is paused CDP might not respond to queries to the target, therefore, any awaited CDP calls in the interceptor might lead to a deadlock. The interceptor should only be used to schedule CDP calls and should not be able to delay runIfWaitingForDebugger calls.

2022-12-17 14:49 UTC, kblok commented
@OrKoN exactly. If `Page.#onAttachedToTarget` is not `async` (I just removed the keyword in the function). There is no need to await for it. There is no async code in that function.

2022-12-17 17:26 UTC, OrKoN commented
ah apologies, totally misread the title and the diff in the morning.

2022-12-17 17:27 UTC, OrKoN approved these changes

2022-12-17 17:47 UTC, merged

2023-01-14 10:13 UTC, Cklim143 commented
``