fix: `page.goto` error throw (#9523)
puppeteer/puppeteer pull request #9577
Opened 2023-01-25 00:14 UTC by Rafael-Martins

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
no

**Summary**

Remove the error throw on the `navigate` method, in order to get [#9523](https://github.com/puppeteer/puppeteer/issues/9523) fixed

2023-01-25 00:22 UTC, Rafael-Martins commented
Hey guys, I'm new here, please tell me if this change makes sense!

2023-01-25 07:59 UTC, OrKoN requested changes
I think we cannot just remove the error message here. Did you find out why the browser handles the errors differently? perhaps it should be fixed upstream first.

2023-01-25 15:21 UTC, Rafael-Martins commented
> I think we cannot just remove the error message here. Did you find out why the browser handles the errors differently? perhaps it should be fixed upstream first.

Oh, I see, just saw some tests failing because of this as well, I'm digging into it!

2023-01-25 19:42 UTC, Rafael-Martins commented
The issue only happen in chrome, looking at the  I see that `errorText` is returned when the navigation is failed, so chrome is considering the `404` as a navigation error. Can we filter it like my last commit?

It appears that the issue at hand is specific to the Chrome browser. By consulting the documentation for the [devtools-protocol docs](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate) it can be observed that the errorText property is provided when a navigation failure occurs. In this case, Chrome is interpreting a 404 error as a navigation failure. To address this, it may be possible to implement a filter similar to the one utilized in a previous commit, in order to bypass this error.

2023-01-26 08:04 UTC, OrKoN commented
@Rafael-Martins so when the browser treats the navigation as an error it shows a different kind of the error page I think which is usually restricted to CDP. What is the situation after the navigation errors, can you still evaluate or navigate the page to a different URL?

2023-01-26 08:04 UTC, OrKoN requested changes
Let's add a test for covering this scenario

2023-02-03 19:02 UTC, Rafael-Martins commented
> @Rafael-Martins so when the browser treats the navigation as an error it shows a different kind of the error page I think which is usually restricted to CDP. What is the situation after the navigation errors, can you still evaluate or navigate the page to a different URL?

I tested and the navigate works normally, I added 2 tests that covers the `404`,`505` responses with empty body, they look similar or almost redundant, if you think that it is not needed I can remove.

2023-02-06 07:00 UTC, OrKoN commented on test/src/navigation.spec.ts
> +    it('should not throw a error when get a 404 response with empty body', async () => {
```suggestion
    it('should not throw an error for a 404 response with an empty body', async () => {
```

2023-02-06 07:01 UTC, OrKoN commented on test/src/navigation.spec.ts
> +    it('should not throw a error when get a 500 response with empty body', async () => {
```suggestion
    it('should not throw an error for a 500 response with an empty body', async () => {
```

2023-02-06 07:01 UTC, OrKoN approved these changes

2023-02-06 09:40 UTC, merged