chore: Extract Context to allow emitting only to it
puppeteer/puppeteer pull request #9742
Opened 2023-02-23 14:55 UTC by Lightning00Blade

2023-02-27 12:23 UTC, jrandolf approved these changes

2023-02-27 12:24 UTC, jrandolf requested changes
Do we need tests for this?

2023-02-27 12:29 UTC, Lightning00Blade commented
> Do we need tests for this?
What part do you think may need separate tests? ( I think the only part we should test is the BiDiSerializer)
I think having seeing that the Test Expecatation are the same is OK for now.

2023-02-28 10:09 UTC, jrandolf approved these changes

2023-02-28 10:10 UTC, merged